export const SET_MOVED_SHIP_SIZE = 'SET_MOVED_SHIP_SIZE'
export const SET_MOVED_SHIP_IS_POSITION_CORRECT = 'SET_MOVED_SHIP_IS_POSITION_CORRECT'
export const SET_MOVED_SHIP_HEAD_POSITION = 'SET_MOVED_SHIP_HEAD_POSITION'
export const SET_MOVED_SHIP_HORIZONTAL_POSITION = 'SET_MOVED_SHIP_HORIZONTAL_POSITION'

export const UPDATE_SHIPS = 'UPDATE_SHIPS'
export const SET_SHIPS_HORIZONTAL_POSITION = 'SET_SHIPS_HORIZONTAL_POSITION'

export const PLACE_USER_SHIP = 'PLACE_USER_SHIP'
